
filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /opt/zookeeper/logs/*.log
  #json.keys_under_root: true
  #json.add_error_key: true
  #include_lines: ['^ERR', '^WARN']
  #exclude_files: ['.gz$']
  #fields:
  #  level: debug
  #  review: 1


filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

fields:
  appname: zookeper
  version: 0.0.1

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_host_metadata: ~
#  - add_docker_metadata: ~
#  - add_kubernetes_metadata: ~
