apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: edgeone
  labels:
    app: zookeeper
    serviceType: core
    ge_domain: platform
    kafka: 'true'
    foss: 'true'
    event-bus: 'true'
    message-bus: 'true'
    java: 'true'
    orchestration: 'true'
    ge_base_image: ge-ubuntu-generic
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        serviceType: core
        ge_domain: platform
        kafka: 'true'
        foss: 'true'
        event-bus: 'true'
        message-bus: 'true'
        java: 'true'
        orchestration: 'true'
        ge_base_image: ge-ubuntu-generic
    spec:
      containers:
      - name: zookeeper
        image: germanedge-docker.artifactory.new-solutions.com/edge-one/zookeeper:4.17.0
        imagePullPolicy: Always
        command: []
        ports:
        - containerPort: 2181
          name: port-0
        env:
        - name: EXT_CA_CERT
          valueFrom:
            secretKeyRef:
              key: ext_ca_cert
              name: external-ca-cert-secret
              optional: true
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: edgeone-zookeeper-pv
          mountPath: /opt/zookeeper/data
          subPath: optzookeeperdata
        resources:
          limits:
            memory: "512M"
            ephemeral-storage: "1200M"
          requests:
            ephemeral-storage: "1000M"
        livenessProbe:
          httpGet:
            port: 7071
            path: /metrics
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            port: 7071
            path: /metrics
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            port: 7071
            path: /metrics
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
      initContainers: []
      imagePullSecrets:
      - name: artifactory
      volumes:
      - name: edgeone-zookeeper-pv
        persistentVolumeClaim:
          claimName: edgeone-zookeeper-pv-claim
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 1000
  replicas: 1
  strategy:
    type: Recreate
---
